### ISSUE TITLE
Feeds of botnet command and control servers: h3x is offline

### ISSUE THREAD

**Issue by ghost** [CERT-Polska/proactive-detection-survey#1]
The URL
https://tracker.h3x.eu
listed in
https://github.com/CERT-Polska/proactive-detection-survey/blob/master/information_sources_survey.md
under "Feeds of botnet command and control servers" is not reachable and seems to be down

**Comment by PBia** [comment]
Thank you, it is currently really down. We will check it and update info accordingly.

**Comment by PBia** [comment]
Hi,
it's again online. But thanks for pointing this out :-) 
We will leave it in the list, but monitor its availability.

**Comment by ghost** [comment]
> Hi,
> it's again online. But thanks for pointing this out :-)
> We will leave it in the list, but monitor its availability.

Times out for me (again)
