### ISSUE TITLE
Malware intelligence: Virustotal Intelligence "is going away"

### ISSUE THREAD

**Issue by ghost** [CERT-Polska/proactive-detection-survey#3]
If 'Virustotal Intelligence" means https://www.virustotal.com/intelligence/ it seems that this is discontinued:

>  Going away! We are building a holistic malware hunting platform to give good the advantage. VirusTotal Intelligence is becoming part of VT Enterprise, a service that also encompasses VT Hunting, VT Graph and VT API.

**Comment by PBia** [comment]
Thanks for pointing this out. We have added "Enterprise" in https://github.com/CERT-Polska/proactive-detection-survey/commit/0cedb1f690e96c41b3aa22730932ecbb1457c9fd
